services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_HOST: ${host}
      POSTGRES_PORT: ${port}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build: .
    container_name: esther
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
